import React from 'react';
import { FaBrain } from 'react-icons/fa';
import FeedbackButtons from './FeedbackButtons';

const AIInsight = ({ insight }) => {
  if (!insight || !insight.text) {
    return (
      <div className="dashboard-card">
        <h2><FaBrain /> AI Insight of the Day</h2>
        <div className="card-content">
          <p>No insight available at the moment.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="dashboard-card">
      <h2><FaBrain /> AI Insight of the Day</h2>
      <div className="ai-insight">
        <div className="ai-insight-text">{insight.text}</div>
        {insight.model && (
          <div className="ai-insight-meta">
            Generated by {insight.model}
          </div>
        )}
      </div>
      {insight.content_hash && (
        <FeedbackButtons
          contentType="insight"
          contentHash={insight.content_hash}
        />
      )}
    </div>
  );
};

export default AIInsight;

